name: CI

on:
  push:
    paths:
      - 'pypoetry_template/**'
      - 'tests/**'
      - '.github/**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: snok/install-poetry@v1
      - run: poetry install --no-interaction
      - run: poetry run pytest -s
